### ISSUE TITLE
two questions about dataset

### ISSUE THREAD

**Issue by NankyLiu** [KovenYu/MAR#3]
hallo,thanks for your share!
I've met two errors after running the program！
1.the dataset downloaded is the MSMT17_v2,not the v1,without folder named test and train!
2.in my windows,running the program with the enviroment of anaconda,a bug occurred,
with error statements"Traceback (most recent call last):
  File "src\main.py", line 47, in <module>
    main()
  File "src\main.py", line 14, in main
    args.crop_size, args.padding, args.batch_size//2, False)
  File "C:\Users\Documents\MAR-master\MAR-master\src\utils.py", line 533, in get_transfer_dataloaders
    source_data = FullTraining('data/{}.mat'.format(source))
  File "C:\Users\Documents\MAR-master\MAR-master\src\ReIDdatasets.py", line 108, in __init__
    self.data = np.transpose(temp.value, (0, 3, 2, 1))
  File "h5py\_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py\_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "C:\Users\AppData\Roaming\Python\Python36\site-packages\h5py\_hl\dataset.py", line 250, in value
    return self[()]
  File "h5py\_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py\_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "C:\Users\idriver\AppData\Roaming\Python\Python36\site-packages\h5py\_hl\dataset.py", line 496, in __getitem__
    self.id.read(mspace, fspace, arr, mtype, dxpl=self._dxpl)
  File "h5py\_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py\_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "h5py\h5d.pyx", line 181, in h5py.h5d.DatasetID.read
  File "h5py\_proxy.pyx", line 130, in h5py._proxy.dset_rw
  File "h5py\_proxy.pyx", line 84, in h5py._proxy.H5PY_H5Dread
OSError: Can't read data (inflate() failed)"
I don't know how to solve these problem,please help me,thank you!

**Comment by dinggd** [comment]
This might because of the resources exhaustion on your windows, maybe try a better-configured server?

**Comment by KovenYu** [comment]
@NankyLiu Hi, sorry for the late reply.

1. do you refer to the dataset downloaded from the original website, or my BAIDU link? I checked the BAIDU PAN link, it seemed no problem, and the name of the dataset was "MSMT17.mat" without either V1 or V2

2. as @gddingcs  indicated, it seems that the problem is related to the operation system (see the last two lines of your error message). I do not know how to solve this in Windows. How about trying it in Linux (maybe a server) instead?

**Comment by zsy94** [comment]
hello,thanks for your share!
I also encountered the same problem when I tried to change the data set . I used your code of  MATLAB and other data sets. I ran it and saved them in the format of ".mat".And then I putted it in the data folder to run, and I got this error.
I don't know whether the  code of  MATLAB is need to change ,please help me,thank you!

**Comment by shanglidan** [comment]
@KovenYu Hello,I've met the same problem with NankyLiu. 
And, I run it in  a server with 4 GPU(1080 ti).
I don't know how to solve the problem,please help me,thank you! 

/data/sld/MAR-master/src/utils.py:32: YAMLLoadWarning: calling yaml.load() without Loader=... is deprecated, as the default Loader is unsafe. Please read https://msg.pyyaml.org/load for full details.
  extra_args = yaml.load(f)
python version : 3.6.8 (default, Dec 24 2018, 19:24:27)  [GCC 5.4.0 20160609]
torch  version : 1.0.0.dev20190401

------------------------------------------------------- options --------------------------------------------------------
            batch_size: 368                            beta: 0.2                         crop_size: (384, 128)
               epochs: 20                             gpu: 0,1,2,3                        img_size: (384, 128)
             lamb_1: 0.0002                           lamb_2: 50.0                             lr: 0.0002
              margin: 1.0                         mining_ratio: 0.005                 ml_path: data/ml_Market.dat
               padding: 7               pretrain_path: data/pretrained_weight.pth            print_freq: 100
                resume:                          save_path: runs/debug                       scala_ce: 30.0
             source: MSMT17                          target: Market                            wd: 0.025
------------------------------------------------------------------------------------------------------------------------

data/MSMT17.mat
/usr/local/lib/python3.6/dist-packages/h5py/_hl/dataset.py:313: H5pyDeprecationWarning: dataset.value has been deprecated. Use dataset[()] instead.
  "Use dataset[()] instead.", H5pyDeprecationWarning)
Traceback (most recent call last):
  File "src/main.py", line 46, in <module>
    main()
  File "src/main.py", line 13, in main
    args.crop_size, args.padding, args.batch_size//2, False)
  File "/data/sld/MAR-master/src/utils.py", line 521, in get_transfer_dataloaders
    source_data = FullTraining('data/{}.mat'.format(source))
  File "/data/sld/MAR-master/src/ReIDdatasets.py", line 108, in __init__
    self.data = np.transpose(temp.value, (0, 3, 2, 1))
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "/usr/local/lib/python3.6/dist-packages/h5py/_hl/dataset.py", line 314, in value
    return self[()]
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "/usr/local/lib/python3.6/dist-packages/h5py/_hl/dataset.py", line 573, in __getitem__
    self.id.read(mspace, fspace, arr, mtype, dxpl=self._dxpl)
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "h5py/h5d.pyx", line 181, in h5py.h5d.DatasetID.read
  File "h5py/_proxy.pyx", line 130, in h5py._proxy.dset_rw
  File "h5py/_proxy.pyx", line 84, in h5py._proxy.H5PY_H5Dread
OSError: Can't read data (inflate() failed)

**Comment by KovenYu** [comment]
@shanglidan It seems that an OSError is a general problem related with the OS itself. I would guess it could be due to insufficient RAM memory. You may type "top" into the command line and see how much memory is left on the server. By default it should take no less than 40GB.
